# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

source 'https://github.com/HossamYoussof/NFCTunnel-iOS-SDK.git'
target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'NFCTunnel', '~> 0.1.0'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    # Pods for testing
  end

end
